# Generated by Django 5.0.2 on 2024-02-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
