# Generated by Django 5.0.2 on 2024-03-11 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
